name: Build for win_amd64

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Build FFmpeg and wheel
        uses: ./.github/actions/build-wheel
        with:
          WHL_PLATFORM: "win_amd64"
          ARCH: "x86_64"
          CROSS_COMPILE: "x86_64-w64-mingw32"
          CROSS_COMPILE_PKG_SUFFIX: "mingw-w64-x86-64"
          PLATFORM: "mingw32"
